### ISSUE TITLE
When using in combination with the sitemap plugin an exception is thrown

### ISSUE THREAD

**Issue by bnordland** [vdomah/blogviews#4]
When I have the sitemap plugin also installed, and set the sitemap to have all blog posts, I get the following error when viewing the sitemap.

Steps to recreate:

1. Install sitemap plugin and the blogviews plugin
2. Add the type of "all blog posts" to the sitemap
3. View the sitemap, and it throws a 500 error with the following.

BadMethodCallException: The component 'RainLab\Blog\Components\Post' does not contain a method 'getController'. in /html/modules/cms/classes/ComponentBase.php:278
Stack trace:
#0 **/html/plugins/vdomah/blogviews/Plugin.php(65): Cms\Classes\ComponentBase->__call('getController', Array)**
#1 [internal function]: Vdomah\BlogViews\Plugin->Vdomah\BlogViews\{closure}(Object(RainLab\Blog\Components\Post))
#2 /html/vendor/october/rain/src/Extension/ExtendableTrait.php(56): call_user_func(Object(Closure), Object(RainLab\Blog\Components\Post))
#3 /html/vendor/october/rain/src/Extension/Extendable.php(27): October\Rain\Extension\Extendable->extendableConstruct()
#4 /html/modules/cms/classes/ComponentBase.php(101): October\Rain\Extension\Extendable->__construct()
#5 [internal function]: Cms\Classes\ComponentBase->__construct(NULL, Array)
#6 /html/vendor/laravel/framework/src/Illuminate/Container/Container.php(780): ReflectionClass->newInstanceArgs(Array)
#7 /html/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('\\RainLab\\Blog\\C...', Array)
#8 /html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('\\RainLab\\Blog\\C...', Array)
#9 /html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Foundation\Application->make('\\RainLab\\Blog\\C...', Array)
#10 /html/modules/cms/classes/ComponentManager.php(214): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#11 /html/modules/cms/classes/CmsCompoundObject.php(223): Cms\Classes\ComponentManager->makeComponent('blogPost', NULL, Array)
#12 /html/modules/cms/classes/CmsCompoundObject.php(306): Cms\Classes\CmsCompoundObject->getComponent('blogPost')
#13 /html/plugins/rainlab/blog/models/Post.php(493): Cms\Classes\CmsCompoundObject->getComponentProperties('blogPost')
#14 /html/plugins/rainlab/blog/models/Post.php(471): RainLab\Blog\Models\Post::getPostPageUrl('blog/post', Object(RainLab\Blog\Models\Post), Object(Cms\Classes\Theme))
#15 /html/plugins/rainlab/blog/Plugin.php(157): RainLab\Blog\Models\Post::resolveMenuItem(Object(RainLab\Sitemap\Classes\DefinitionItem), 'sitemap.xml', Object(Cms\Classes\Theme))
#16 [internal function]: RainLab\Blog\Plugin->RainLab\Blog\{closure}('all-blog-posts', Object(RainLab\Sitemap\Classes\DefinitionItem), 'sitemap.xml', Object(Cms\Classes\Theme))
#17 /html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#18 /html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Events\Dispatcher->fire('pages.menuitem....', Array)
#19 /html/plugins/rainlab/sitemap/models/Definition.php(102): Illuminate\Support\Facades\Facade::__callStatic('fire', Array)
#20 /html/plugins/rainlab/sitemap/routes.php(10): RainLab\Sitemap\Models\Definition->generateSitemap()
#21 [internal function]: System\Classes\PluginManager->{closure}()
#22 /html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(155): call_user_func_array(Object(Closure), Array)
#23 /html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(130): Illuminate\Routing\Route->runCallable(Object(Illuminate\Http\Request))
#24 /html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 /html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 /html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 /html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#47 /html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 /html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 /html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#54 /html/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#55 {main}

**Comment by vdomah** [comment]
fixed
