### ISSUE TITLE
Call to a member function getKey() on null while trying to view category page

### ISSUE THREAD

**Issue by m-paniez9292** [vdomah/blogviews#6]
Hi,
I encountered a little problem while trying yo view the category page.
I get :
ERROR We're sorry, but an unhandled error occurred. Please see the details below.
Call to a member function getKey() on null C:\xampp\htdocs\yans-news\plugins\vdomah\blogviews\Plugin.php line 85

I finally succeeded by replacing the line 85 by the code below 
```
if(is_null($post)){
                return;
            }else{
                $cookName = self::POST_VIEWED . $post->getKey();
            }:
```
[From Octobercms forum (thanks to robertmaku32322)](https://octobercms.com/plugin/support/vdomah-blogviews/call-to-a-member-function-getkey-on-null-while-trying-yo-view-category-page)

Thanks

**Comment by vdomah** [comment]
fixed in 1.0.10 version. Thanks for report
